const {chromium}=require('playwright');
const fs=require('fs');
const {spawn}=require('child_process');
(async()=>{
 const server=spawn('python',['-m','http.server','3001'],{cwd:'/home/user/workspace/degen-detox/build/web',stdio:'ignore'});
 process.on('exit',()=>server.kill());
 await new Promise(r=>setTimeout(r,700));
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.setDefaultTimeout(6000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3001',{waitUntil:'networkidle'});
 await page.waitForSelector('flutter-view');
 await page.waitForTimeout(3000);
 const enable=page.locator('flt-semantics-placeholder');
 if(await enable.count()) await enable.evaluate(e=>e.click());
 await page.waitForTimeout(500);
 await page.screenshot({path:'/home/user/workspace/degen-desktop.png'});
 console.log('BODY',await page.locator('body').innerText());
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(800);
 await page.screenshot({path:'/home/user/workspace/degen-mobile.png'});
 console.log('BUTTONS',await page.getByRole('button').allTextContents());
 await page.getByRole('button',{name:'Set up your morning',exact:true}).click();
 await page.getByText('Lifetime Pro. No subscriptions. No monthly bills.',{exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-pro.png'});
 await page.getByRole('button',{name:'Explore Pro preview',exact:true}).last().click();
 await page.getByRole('button',{name:'Set up your morning',exact:true}).click();
 await page.getByText('Protected hours',{exact:false}).waitFor();
 console.log('MORNING DOM',await page.locator('body').innerText());
 console.log('MORNING LABELS',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByRole('checkbox',{name:'4 hours',exact:true}).click();
 await page.getByRole('button',{name:/Choose apps/}).click();
 await page.getByRole('checkbox',{name:'Binance',exact:true}).click();
 await page.getByRole('button',{name:'Save',exact:true}).last().click();
 await page.getByRole('button',{name:'Save',exact:true}).last().click();
 await page.getByText('Saved',{exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-morning.png'});
 await page.getByRole('button',{name:'Close',exact:true}).last().click();
 await page.getByRole('button',{name:/Impulse Check/}).click();
 await page.getByRole('textbox').fill('FOMO after checking the chart');
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.getByText('Check-in saved on this device.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:/Breathe, not refresh/}).click();
 await page.getByRole('button',{name:/Belly Breathing/}).click();
 await page.getByRole('button',{name:'Start session',exact:true}).click();
 await page.waitForTimeout(1200);
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await page.getByRole('button',{name:'Resume',exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-breathe.png'});
 await page.getByRole('button',{name:'Back',exact:true}).click();
 console.log('NAV',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByRole('tab',{name:/Rituals/}).click();
 await page.getByRole('button',{name:/Touch Grass/}).click();
 await page.getByRole('checkbox',{name:'8 hours',exact:true}).click();
 await page.getByRole('button',{name:'Preview reminder',exact:true}).click();
 await page.waitForTimeout(400);
 await page.screenshot({path:'/home/user/workspace/degen-grass-screen.png'});
 await page.getByRole('button',{name:'Close',exact:true}).first().click();
 await page.getByRole('tab',{name:/Settings/}).click();
 await page.getByText('English',{exact:true}).click();
 console.log('LANGUAGES',await page.locator('body').innerText());
 console.log('LANG-LABELS',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByRole('menuitem',{name:'Lietuvių',exact:true}).click();
 await page.getByText('Privatumas ir sauga',{exact:true}).waitFor();
 await page.getByRole('tab',{name:/Šiandien/}).click();
 await page.mouse.move(1,1);
 await page.waitForTimeout(1200);
 await page.screenshot({path:'/home/user/workspace/degen-lt.png'});
 await page.getByRole('button',{name:'Šviesi tema',exact:true}).click();
 await page.mouse.move(1,1);
 await page.waitForTimeout(1200);
 await page.screenshot({path:'/home/user/workspace/degen-light.png'});
 console.log('ERRORS',errors);
 fs.writeFileSync('/home/user/workspace/degen-qa-initial.json',JSON.stringify({errors},null,2));
 await browser.close();
 server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
