const {chromium}=require('playwright');
const fs=require('fs');
const {spawn}=require('child_process');
(async()=>{
 const server=spawn('python',['-m','http.server','3001'],{cwd:'/home/user/workspace/degen-detox/build/web',stdio:'ignore'});
 process.on('exit',()=>server.kill());
 await new Promise(r=>setTimeout(r,700));
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.setDefaultTimeout(6000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3001',{waitUntil:'networkidle'});
 await page.waitForSelector('flutter-view',{timeout:30000});
 await page.waitForTimeout(3000);
 const enable=page.locator('flt-semantics-placeholder');
 if(await enable.count()) await enable.evaluate(e=>e.click());
 await page.waitForTimeout(500);
 await page.screenshot({path:'/home/user/workspace/degen-desktop.png'});
 console.log('BODY',await page.locator('body').innerText());
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(800);
 await page.screenshot({path:'/home/user/workspace/degen-mobile.png'});
 console.log('BUTTONS',await page.getByRole('button').allTextContents());
 await page.getByRole('button',{name:'Set up blocking',exact:true}).click();
 await page.getByText('Lifetime Pro. No subscriptions. No monthly bills.',{exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-pro.png'});
 await page.getByRole('button',{name:'Explore Pro preview',exact:true}).last().click();
 await page.getByRole('button',{name:'Set up blocking',exact:true}).click();
 await page.getByText('Protected hours',{exact:false}).waitFor();
 console.log('MORNING DOM',await page.locator('body').innerText());
 console.log('MORNING LABELS',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByText('Wake-up time 8:00 AM',{exact:true}).click();
 await page.getByRole('textbox',{name:'Minutes',exact:true}).click();
 await page.waitForTimeout(150);
 await page.keyboard.type('45');
 await page.getByRole('textbox',{name:'Hours',exact:true}).click();
 await page.waitForTimeout(150);
 await page.keyboard.type('7');
 await page.waitForTimeout(150);
 await page.screenshot({path:'/home/user/workspace/degen-v07-numeric-time.png'});
 await page.getByRole('button',{name:'Save',exact:true}).last().click();
 await page.waitForTimeout(300);
 if(!(await page.locator('body').innerText()).includes('7:45')) throw Error('Numeric time not applied');
 await page.getByRole('checkbox',{name:'4 hours',exact:true}).click();
 await page.getByRole('button',{name:/Choose apps/}).click();
 await page.getByRole('textbox',{name:'Search apps',exact:true}).fill('  bina  ');
 await page.getByRole('checkbox',{name:'Binance',exact:true}).click();
 await page.waitForTimeout(300);
 await page.screenshot({path:'/home/user/workspace/degen-v06-search.png'});
 await page.getByRole('textbox',{name:'Search apps',exact:true}).click();
 await page.keyboard.press('ControlOrMeta+A');
 await page.keyboard.type('nothing matches',{delay:30});
 await page.waitForTimeout(350);
 console.log('EMPTY SEARCH', await page.locator('body').innerText());
 console.log('EMPTY LABELS', await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.screenshot({path:'/home/user/workspace/degen-v06-empty.png'});
 await page.getByText('No matching apps. Try another name.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Clear search',exact:true}).click();
 await page.getByRole('checkbox',{name:'Selected only · 1',exact:true}).click();
 await page.waitForTimeout(300);
 if(await page.getByRole('checkbox',{name:'TradingView',exact:true}).count()) throw Error('Selected filter leaked unselected app');
 await page.getByRole('button',{name:'Save · 1',exact:true}).click();
 await page.getByText('Selected apps · 1',{exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-v06-selected.png'});
 console.log('SELECTED LABELS',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 if (!(await page.locator('body').innerText()).includes('Binance') &&
     !await page.locator('[aria-label="Binance"]').count()) throw Error('Missing selected name');
 await page.getByRole('button',{name:/Choose apps/}).click();
 await page.getByRole('checkbox',{name:'Telegram',exact:true}).click();
 await page.getByRole('button',{name:'Close',exact:true}).last().click();
 await page.getByText('Selected apps · 1',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Save',exact:true}).last().click();
 await page.getByText('Saved',{exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-morning.png'});
 await page.getByRole('button',{name:'Close',exact:true}).last().click();
 await page.getByRole('button',{name:/Impulse Check/}).click();
 await page.getByRole('textbox').fill('FOMO after checking the chart');
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await page.getByText('Check-in saved on this device.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 for (let i=0;i<2;i++) {
   await page.getByRole('button',{name:/Impulse Check/}).click();
   await page.getByRole('textbox').click();
   await page.waitForTimeout(150);
   await page.keyboard.type(i===0?'A quiet morning':'Checking after a notification');
   await page.keyboard.press('Tab');
   const slider=await page.getByRole('slider').boundingBox();
   await page.mouse.click(slider.x+slider.width*(i===0?.25:.8),slider.y+slider.height/2);
   await page.waitForTimeout(150);
   await page.getByRole('button',{name:'Save',exact:true}).click();
   await page.getByText('Check-in saved on this device.',{exact:false}).waitFor();
   if(i===0) await page.getByRole('button',{name:'Close',exact:true}).click();
 }
 await page.getByRole('button',{name:'Your urge patterns',exact:true}).last().click();
 await page.getByText('Check-ins: 3',{exact:true}).waitFor();
 console.log('INSIGHTS',await page.locator('body').innerText());
 await page.getByText(/^Average urge: \d+\.\d\/10$/).first().waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-v08-insights.png'});
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:/Breathing exercises/}).click();
 await page.getByRole('button',{name:/Belly Breathing/}).click();
 await page.getByRole('button',{name:'Start session',exact:true}).click();
 await page.waitForTimeout(1200);
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await page.getByRole('button',{name:'Resume',exact:true}).waitFor();
 await page.screenshot({path:'/home/user/workspace/degen-breathe.png'});
 await page.getByRole('button',{name:'Back',exact:true}).click();
 console.log('NAV',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByRole('tab',{name:/Rituals/}).click();
 await page.getByRole('button',{name:/Touch Grass/}).click();
 await page.getByRole('checkbox',{name:'8 hours',exact:true}).click();
 await page.getByRole('button',{name:'Preview reminder',exact:true}).click();
 await page.waitForTimeout(400);
 await page.screenshot({path:'/home/user/workspace/degen-grass-screen.png'});
 await page.getByRole('button',{name:'Close',exact:true}).first().click();
 await page.getByRole('tab',{name:/Settings/}).click();
 await page.getByText('English',{exact:true}).click();
 console.log('LANGUAGES',await page.locator('body').innerText());
 console.log('LANG-LABELS',await page.locator('[aria-label]').evaluateAll(e=>e.map(x=>[x.getAttribute('role'),x.getAttribute('aria-label')])));
 await page.getByRole('menuitem',{name:'Lietuvių',exact:true}).click();
 await page.getByText('Privatumas ir sauga',{exact:true}).waitFor();
 await page.getByRole('tab',{name:/Šiandien/}).click();
 await page.mouse.move(1,1);
 await page.waitForTimeout(1200);
 await page.screenshot({path:'/home/user/workspace/degen-lt.png'});
 await page.getByRole('button',{name:'Šviesi tema',exact:true}).click();
 await page.mouse.move(1,1);
 await page.waitForTimeout(1200);
 await page.screenshot({path:'/home/user/workspace/degen-light.png'});
 console.log('ERRORS',errors);
 if(errors.length) throw Error('Browser page errors: '+errors.join('; '));
 fs.writeFileSync('/home/user/workspace/degen-qa-initial.json',JSON.stringify({errors},null,2));
 await browser.close();
 server.kill();
})().catch(e=>{console.error(e);process.exit(1)});
